export type FormlyTemplate =
  | 'Date'
  | 'DateTime'
  | 'BoolSelectButton'
  | 'BoolSwitch'
  | 'Checkbox'
  | 'Dropdown'
  | 'FileUpload'
  | 'DropdownWithEchoFields'
  | 'MultiSelectDropdown'
  | 'AutoComplete'
  | 'MultiSelectAutoComplete'
  | 'ShortString'
  | 'LongString'
  | 'Number'
  | 'DetailForm';
